import './globals.css';
import { Inter } from 'next/font/google';

import { ThemeProvider } from '@/context/ThemeContext';
import ClientThemeWrapper from '@/context/ClientThemeWrapper';



const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}) {

  return (
    <html lang='en'>

      <body data-theme="dark" className={inter.className}>
        <ThemeProvider>
          <ClientThemeWrapper>
            <div className=''>
              {children}
            </div>
          </ClientThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}