import './globals.css';
import { Inter } from 'next/font/google';

import { getTheme } from '../lib/getTheme';
import Navbar from '@/components/navigation/Navbar';
import Footer from '@/components/Footer';
import { ThemeProvider } from '@/context/ThemeContext';
import ClientThemeWrapper from '@/context/ClientThemeWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang='en'>
      <head>
        <script dangerouslySetInnerHTML={{ __html: getTheme }} />
      </head>
      <body data-theme="dark" className={inter.className}>
        <ThemeProvider>
          <ClientThemeWrapper>
            <div className=''>
              <Navbar />
              {children}
              <Footer />
            </div>
          </ClientThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}